"""Add summary column to Resource model

Revision ID: 69bfa202bce2
Revises: f2cececf6baf
Create Date: 2024-07-23 20:34:51.183510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bfa202bce2'
down_revision = 'f2cececf6baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
