"""Add summary column to Resource model

Revision ID: f2cececf6baf
Revises: 
Create Date: 2024-07-23 20:29:56.885038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2cececf6baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.FLOAT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('grade', sa.FLOAT(), nullable=False),
    sa.Column('attendance', sa.BLOB(), nullable=True),
    sa.Column('semester_marks', sa.BLOB(), nullable=True),
    sa.Column('preferred_subject', sa.VARCHAR(length=100), nullable=True),
    sa.Column('learning_style', sa.VARCHAR(length=100), nullable=True),
    sa.Column('strengths', sa.VARCHAR(length=500), nullable=True),
    sa.Column('weaknesses', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
